export const QueryParams = {
  page: 'page',
  limit: 'limit',
  type: 'type',
  order_by: 'order_by',
  score: 'score',
  min_score: 'min_score',
  max_score: 'max_score',
  filter: 'filter',
  preliminary: 'preliminary',
  spoilers: 'spoilers',
  unapproved: 'unapproved',
  search: 'q',
  status: 'status',
  rating: 'rating',
  no_adults: 'sfw',
  genres: 'genres',
  genres_exclude: 'genres_exclude',
  sort: 'sort',
  letter: 'letter',
  producers: 'producers',
  start_date: 'start_date',
  end_date: 'end_date',
  category: 'category',
  continuing: 'continuing'
}